const ListMenu = [
    {
        title: 'PLats',
        data: [
        {
            key: 1,
            title: 'Toast aux poulets',
            ingredients: 'poulet, viande hachée, persil',
            price: 10.500,
            star: 4.2,
            img: require('../../../../assets/images/MenuCli/food/food1.png'),
            quantity: 0,
        },
        {
            key: 2,
            title: 'Soupe aux langues de chats',
            ingredients: 'chat, poivre, huitre',
            price: 25.000,
            star: 3.5,
            img: require('../../../../assets/images/MenuCli/food/food2.png'),
            quantity: 0,
        },
        {
            key: 3,
            title: 'Spaghetti à la façon chinoise',
            ingredients: 'ravitoto, saucisse, courgette',
            price: 15.700,
            star: 3.8,
            img: require('../../../../assets/images/MenuCli/food/food3.png'),
            quantity: 0,
        },
        {
            key: 4,
            title: 'Fruits de mer crûs',
            ingredients: 'calmar, crevette, champignon',
            price: 8.000,
            star: 2.9,
            img: require('../../../../assets/images/MenuCli/food/food4.png'),
            quantity: 0,
        },
        {
            key: 5,
            title: 'Tarte à la crème',
            ingredients: 'yaourt, chantilly, beurre',
            price: 6.000,
            star: 4.5,
            img: require('../../../../assets/images/MenuCli/food/food5.png'),
            quantity: 0,
        },
        {
            key: 6,
            title: 'Sauce aux chilli',
            ingredients: 'chilli, tomate, moutarde',
            price: 5.000,
            star: 4.8,
            img: require('../../../../assets/images/MenuCli/food/food6.png'),
            quantity: 0,
        },
        ],
    },

    {
        title: 'Accompagnements',
        data: [
        {
            key: 7,
            title: 'Toast aux chèvres',
            ingredients: 'poulet, viande hachée, persil',
            price: 18.900,
            star: 4.9,
            img: require('../../../../assets/images/MenuCli/food/food1.png'),
            quantity: 0,
        },
        {
            key: 8,
            title: 'Soupe chinoise',
            ingredients: 'chat, poivre, huitre',
            price: 6.000,
            star: 3.8,
            img: require('../../../../assets/images/MenuCli/food/food2.png'),
            quantity: 0,
        },
        {
            key: 9,
            title: 'Spaghetti à la bolognaise',
            ingredients: 'ravitoto, saucisse, courgette',
            price: 23.600,
            star: 3.2,
            img: require('../../../../assets/images/MenuCli/food/food3.png'),
            quantity: 0,
        },
        {
            key: 10,
            title: 'Fruits de Betsimitatatra',
            ingredients: 'calmar, crevette, champignon',
            price: 18.000,
            star: 3.9,
            img: require('../../../../assets/images/MenuCli/food/food4.png'),
            quantity: 0,
        },
        {
            key: 11,
            title: 'Glace à la crème',
            ingredients: 'yaourt, chantilly, beurre',
            price: 3.200,
            star: 4.2,
            img: require('../../../../assets/images/MenuCli/food/food5.png'),
            quantity: 0,
        },
        {
            key: 12,
            title: 'Sauce sacrée',
            ingredients: 'chilli, tomate, moutarde',
            price: 8.000,
            star: 4.6,
            img: require('../../../../assets/images/MenuCli/food/food6.png'),
            quantity: 0,
        },
        ],
    },

    {
        title: 'Desserts',
        data: [
        {
            key: 13,
            title: 'Milk-Shake',
            ingredients: 'poulet, viande hachée, persil',
            price: 18.000,
            star: 4.9,
            img: require('../../../../assets/images/MenuCli/food/food1.png'),
            quantity: 0,
        },
        {
            key: 14,
            title: 'Yaourt à la menthe',
            ingredients: 'chat, poivre, huitre',
            price: 6.400,
            star: 3.8,
            img: require('../../../../assets/images/MenuCli/food/food2.png'),
            quantity: 0,
        },
        {
            key: 15,
            title: 'Glace aux pépites Choco',
            ingredients: 'ravitoto, saucisse, courgette',
            price: 23.000,
            star: 3.2,
            img: require('../../../../assets/images/MenuCli/food/food3.png'),
            quantity: 0,
        },
        {
            key: 16,
            title: 'Tarte à la confiture',
            ingredients: 'calmar, crevette, champignon',
            price: 18.000,
            star: 3.9,
            img: require('../../../../assets/images/MenuCli/food/food4.png'),
            quantity: 0,
        },
        {
            key: 17,
            title: 'Banane au miel',
            ingredients: 'yaourt, chantilly, beurre',
            price: 3.100,
            star: 4.2,
            img: require('../../../../assets/images/MenuCli/food/food5.png'),
            quantity: 0,
        },
        {
            key: 18,
            title: 'Thé glacé',
            ingredients: 'chilli, tomate, moutarde',
            price: 8.000,
            star: 4.6,
            img: require('../../../../assets/images/MenuCli/food/food6.png'),
            quantity: 0,
        },
        ],
  },

];

export default ListMenu;