const SECTIONS = [
    {
        title: 'PLats',
        data: [
        {
            key: '1',
            title: 'Toast aux poulets',
            ingred: 'poulet, viande hachée, persil',
            cost: '10 000 MGA',
            star: '4.2',
            img: require('../../../../assets/images/MenuCli/food/food1.png'),
        },
        {
            key: '2',
            title: 'Soupe aux langues de chats',
            ingred: 'chat, poivre, huitre',
            cost: '25 000 MGA',
            star: '3.5',
            img: require('../../../../assets/images/MenuCli/food/food2.png'),
        },
        {
            key: '3',
            title: 'Spaghetti à la façon chinoise',
            ingred: 'ravitoto, saucisse, courgette',
            cost: '15 000 MGA',
            star: '3.8',
            img: require('../../../../assets/images/MenuCli/food/food3.png'),
        },
        {
            key: '4',
            title: 'Fruits de mer crûs',
            ingred: 'calmar, crevette, champignon',
            cost: '8 000 MGA',
            star: '2.9',
            img: require('../../../../assets/images/MenuCli/food/food4.png'),
        },
        {
            key: '5',
            title: 'Tarte à la crème',
            ingred: 'yaourt, chantilly, beurre',
            cost: '6 000 MGA',
            star: '4.5',
            img: require('../../../../assets/images/MenuCli/food/food5.png'),
        },
        {
            key: '6',
            title: 'Sauce aux chilli',
            ingred: 'chilli, tomate, moutarde',
            cost: '5 000 MGA',
            star: '4.8',
            img: require('../../../../assets/images/MenuCli/food/food6.png'),
        },
        ],
    },

    {
        title: 'Accompagnements',
        data: [
        {
            key: '1',
            title: 'Toast aux chèvres',
            ingred: 'poulet, viande hachée, persil',
            cost: '18 000 MGA',
            star: '5.0',
            img: require('../../../../assets/images/MenuCli/food/food1.png'),
        },
        {
            key: '2',
            title: 'Soupe chinoise',
            ingred: 'chat, poivre, huitre',
            cost: '6 000 MGA',
            star: '3.8',
            img: require('../../../../assets/images/MenuCli/food/food2.png'),
        },
        {
            key: '3',
            title: 'Spaghetti à la bolognaise',
            ingred: 'ravitoto, saucisse, courgette',
            cost: '23 000 MGA',
            star: '3.2',
            img: require('../../../../assets/images/MenuCli/food/food3.png'),
        },
        {
            key: '4',
            title: 'Fruits de Betsimitatatra',
            ingred: 'calmar, crevette, champignon',
            cost: '18 000 MGA',
            star: '3.9',
            img: require('../../../../assets/images/MenuCli/food/food4.png'),
        },
        {
            key: '5',
            title: 'Glace à la crème',
            ingred: 'yaourt, chantilly, beurre',
            cost: '3 000 MGA',
            star: '4.2',
            img: require('../../../../assets/images/MenuCli/food/food5.png'),
        },
        {
            key: '6',
            title: 'Sauce sacrée',
            ingred: 'chilli, tomate, moutarde',
            cost: '8 000 MGA',
            star: '4.6',
            img: require('../../../../assets/images/MenuCli/food/food6.png'),
        },
        ],
    },

    {
        title: 'Desserts',
        data: [
        {
            key: '1',
            title: 'Milk-Shake',
            ingred: 'poulet, viande hachée, persil',
            cost: '18 000 MGA',
            star: '5.0',
            img: require('../../../../assets/images/MenuCli/food/food1.png'),
        },
        {
            key: '2',
            title: 'Yaourt à la menthe',
            ingred: 'chat, poivre, huitre',
            cost: '6 000 MGA',
            star: '3.8',
            img: require('../../../../assets/images/MenuCli/food/food2.png'),
        },
        {
            key: '3',
            title: 'Glace aux pépites Choco',
            ingred: 'ravitoto, saucisse, courgette',
            cost: '23 000 MGA',
            star: '3.2',
            img: require('../../../../assets/images/MenuCli/food/food3.png'),
        },
        {
            key: '4',
            title: 'Tarte à la confiture',
            ingred: 'calmar, crevette, champignon',
            cost: '18 000 MGA',
            star: '3.9',
            img: require('../../../../assets/images/MenuCli/food/food4.png'),
        },
        {
            key: '5',
            title: 'Banane au miel',
            ingred: 'yaourt, chantilly, beurre',
            cost: '3 000 MGA',
            star: '4.2',
            img: require('../../../../assets/images/MenuCli/food/food5.png'),
        },
        {
            key: '6',
            title: 'Thé glacé',
            ingred: 'chilli, tomate, moutarde',
            cost: '8 000 MGA',
            star: '4.6',
            img: require('../../../../assets/images/MenuCli/food/food6.png'),
        },
        ],
  },

];

export default SECTIONS;